# SPDX-FileCopyrightText: GitHub, Inc.
# SPDX-License-Identifier: MIT

"""FastMCP server: narrow execution tools for the fuzzing taskflow.

These tools wrap AFL++, clang, llvm-cov, gcov, etc. so the agent never has to
issue arbitrary shell commands during the build/run/coverage/triage loop.
"""

import glob as _glob
import hashlib
import io
import logging
import os
import re
import shlex
import shutil
import subprocess
import tarfile
from pathlib import Path
from typing import Annotated, Optional

from fastmcp import FastMCP
from pydantic import Field
from seclab_taskflow_agent.path_utils import log_file_name, mcp_data_dir

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filename=log_file_name("mcp_fuzz_runner.log"),
    filemode="a",
)

mcp = FastMCP("FuzzRunner")

WORKSPACE = Path(mcp_data_dir("seclab-taskflows", "fuzz_runner", "FUZZ_RUNNER_DIR"))
FUZZ_BUILDS = WORKSPACE / "builds"
FUZZ_RUNS = WORKSPACE / "runs"
FUZZ_BUILDS.mkdir(parents=True, exist_ok=True)
FUZZ_RUNS.mkdir(parents=True, exist_ok=True)

DEFAULT_TIMEOUT = int(os.environ.get("FUZZ_RUNNER_TIMEOUT") or "300")

AFL_ENV_DEFAULTS = {
    "AFL_SKIP_CPUFREQ": "1",
    "AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES": "1",
    "AFL_BENCH_UNTIL_CRASH": "0",
    "AFL_NO_UI": "1",
}


def _which(name: str) -> str | None:
    return shutil.which(name)


def _afl_install_root() -> Path | None:
    """Locate the AFL++ install prefix by walking up from afl-fuzz."""
    afl = _which("afl-fuzz")
    if not afl:
        return None
    p = Path(afl).resolve().parent.parent
    return p if (p / "lib" / "afl").is_dir() else None


def _afl_driver_archive() -> Path | None:
    root = _afl_install_root()
    if not root:
        return None
    candidate = root / "lib" / "afl" / "libAFLDriver.a"
    return candidate if candidate.is_file() else None


_STANDALONE_DRIVER_C = r"""
/* Auto-generated by seclab_taskflows fuzz_runner.
 * Standalone main() for libFuzzer-style harnesses, used by the coverage build
 * (which is plain clang and cannot link AFL's libAFLDriver.a).
 *
 * Usage:
 *   demo.cov < input          # read from stdin
 *   demo.cov file1 file2 ...  # iterate over files
 */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

extern int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);
__attribute__((weak)) int LLVMFuzzerInitialize(int *argc, char ***argv);

static int run_file(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return 1; }
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return 1; }
    long n = ftell(f);
    if (n < 0) { fclose(f); return 1; }
    rewind(f);
    uint8_t *buf = (uint8_t *)malloc((size_t)n);
    if (!buf) { fclose(f); return 1; }
    size_t got = fread(buf, 1, (size_t)n, f);
    fclose(f);
    LLVMFuzzerTestOneInput(buf, got);
    free(buf);
    return 0;
}

int main(int argc, char **argv) {
    if (LLVMFuzzerInitialize) LLVMFuzzerInitialize(&argc, &argv);
    if (argc <= 1) {
        size_t cap = 4096, len = 0;
        uint8_t *buf = (uint8_t *)malloc(cap);
        if (!buf) return 1;
        for (;;) {
            if (len == cap) {
                cap *= 2;
                uint8_t *nb = (uint8_t *)realloc(buf, cap);
                if (!nb) { free(buf); return 1; }
                buf = nb;
            }
            ssize_t r = read(0, buf + len, cap - len);
            if (r < 0) { free(buf); return 1; }
            if (r == 0) break;
            len += (size_t)r;
        }
        LLVMFuzzerTestOneInput(buf, len);
        free(buf);
        return 0;
    }
    for (int i = 1; i < argc; i++) {
        struct stat st;
        if (stat(argv[i], &st) == 0 && S_ISREG(st.st_mode)) run_file(argv[i]);
    }
    return 0;
}
"""


def _materialise_standalone_driver() -> Path:
    """Write the standalone driver to the workspace and return its path."""
    drv = WORKSPACE / "_aflpp_standalone_driver.c"
    if not drv.is_file() or drv.read_text() != _STANDALONE_DRIVER_C:
        drv.write_text(_STANDALONE_DRIVER_C)
    return drv


def _run(cmd: list[str], cwd: str | None = None, timeout: int = DEFAULT_TIMEOUT,
         env: dict | None = None) -> dict:
    """Run a subprocess; never raise. Return a dict suitable for the agent."""
    real_env = os.environ.copy()
    if env:
        real_env.update(env)
    logging.debug("exec: %s (cwd=%s timeout=%d)", " ".join(shlex.quote(c) for c in cmd), cwd, timeout)
    try:
        proc = subprocess.run(
            cmd, cwd=cwd, env=real_env, capture_output=True, text=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired as e:
        return {
            "exit_code": None, "timed_out": True,
            "stdout": (e.stdout or "")[-4000:] if isinstance(e.stdout, str) else "",
            "stderr": (e.stderr or "")[-4000:] if isinstance(e.stderr, str) else "",
            "cmd": " ".join(shlex.quote(c) for c in cmd),
        }
    except FileNotFoundError as e:
        return {"exit_code": 127, "timed_out": False, "stdout": "", "stderr": str(e),
                "cmd": " ".join(shlex.quote(c) for c in cmd)}
    return {
        "exit_code": proc.returncode, "timed_out": False,
        "stdout": proc.stdout[-4000:], "stderr": proc.stderr[-4000:],
        "cmd": " ".join(shlex.quote(c) for c in cmd),
    }


# ---------------------------------------------------------------------------
# Tooling presence
# ---------------------------------------------------------------------------

@mcp.tool()
def check_tooling() -> dict:
    """Probe for AFL++, clang, llvm-cov, lcov, gcov on PATH. Used at the top of a run."""
    return {
        "afl_clang_lto": _which("afl-clang-lto"),
        "afl_clang_fast": _which("afl-clang-fast"),
        "afl_fuzz": _which("afl-fuzz"),
        "afl_tmin": _which("afl-tmin"),
        "afl_showmap": _which("afl-showmap"),
        "clang": _which("clang"),
        "llvm_cov": _which("llvm-cov"),
        "llvm_profdata": _which("llvm-profdata"),
        "lcov": _which("lcov"),
        "gcov": _which("gcov"),
    }


# ---------------------------------------------------------------------------
# Building harnesses
# ---------------------------------------------------------------------------

def _afl_compiler() -> str:
    return _which("afl-clang-lto") or _which("afl-clang-fast") or "afl-clang-lto"


@mcp.tool()
def compile_harness(
    harness_source: Annotated[str, Field(description="Absolute path to the harness .c/.cc file")],
    output_basename: Annotated[str, Field(description="Basename for built artefacts (no extension); written under the runner workspace")],
    extra_sources: Annotated[list[str] | None, Field(description="Additional .c/.cc files to compile and link with the harness")] = None,
    extra_cflags: Annotated[list[str] | None, Field(description="Additional CFLAGS (e.g. include dirs)")] = None,
    extra_ldflags: Annotated[list[str] | None, Field(description="Additional LDFLAGS (e.g. -L paths)")] = None,
    extra_libs: Annotated[list[str] | None, Field(description="Additional libraries to link, without leading -l (e.g. ['z', 'pthread'])")] = None,
    sanitizers: Annotated[str, Field(description="Comma-separated list, e.g. 'address,undefined'")] = "address,undefined",
    language: Annotated[str, Field(description="'c' or 'c++'")] = "c",
    custom_mutator_source: Annotated[str, Field(description="Optional path to a .c file implementing LLVMFuzzerCustomMutator. Linked into the AFL build only (not the coverage build, which doesn't fuzz). Use write_format_mutator() to generate one for a known format.")] = "",
) -> dict:
    """Build TWO binaries from one harness:

    - ``<basename>.afl`` — instrumented with afl-clang-lto (or afl-clang-fast).
    - ``<basename>.cov`` — instrumented with clang ``-fprofile-instr-generate -fcoverage-mapping``.

    The agent later runs ``.afl`` for fuzzing and ``.cov`` for coverage replay.

    If ``custom_mutator_source`` is set, the AFL build links it in (the
    libAFLDriver shim picks up ``LLVMFuzzerCustomMutator`` automatically).
    The coverage build never includes a custom mutator — it only replays
    inputs.

    Returns a dict describing both builds.
    """
    extra_sources = extra_sources or []
    extra_cflags = extra_cflags or []
    extra_ldflags = extra_ldflags or []
    extra_libs = extra_libs or []

    src = Path(harness_source)
    if not src.is_file():
        return {"ok": False, "error": f"harness source not found: {harness_source}"}

    out_dir = FUZZ_BUILDS
    out_dir.mkdir(parents=True, exist_ok=True)
    afl_bin = out_dir / f"{output_basename}.afl"
    cov_bin = out_dir / f"{output_basename}.cov"

    afl_compiler = _afl_compiler()
    cov_compiler = _which("clang++") if language == "c++" else _which("clang")
    if not cov_compiler:
        return {"ok": False, "error": "clang not found on PATH"}

    afl_driver = _afl_driver_archive()
    if not afl_driver:
        return {"ok": False, "error": "libAFLDriver.a not found (re-run install_afl.sh)"}
    standalone_driver = _materialise_standalone_driver()

    sources = [str(src), *[s for s in extra_sources if s]]
    libs = [f"-l{lib}" for lib in extra_libs if lib]
    san_flag = f"-fsanitize={sanitizers}" if sanitizers else ""

    # C5: custom mutator linked into AFL build only.
    afl_extra_sources: list[str] = []
    if custom_mutator_source:
        if not Path(custom_mutator_source).is_file():
            return {"ok": False, "error": f"custom_mutator_source not found: {custom_mutator_source}"}
        afl_extra_sources.append(custom_mutator_source)

    afl_cmd = [
        afl_compiler, "-g", "-O1", *(["-x", "c++"] if language == "c++" else []),
        *sources, *afl_extra_sources, *extra_cflags, san_flag if san_flag else "",
        *extra_ldflags, str(afl_driver), *libs, "-o", str(afl_bin),
    ]
    afl_cmd = [c for c in afl_cmd if c]

    cov_cmd = [
        cov_compiler, "-g", "-O1", "-fprofile-instr-generate", "-fcoverage-mapping",
        *sources, str(standalone_driver), *extra_cflags,
        *extra_ldflags, *libs, "-o", str(cov_bin),
    ]

    afl_env = AFL_ENV_DEFAULTS.copy()
    afl_env["AFL_USE_ASAN"] = "1" if "address" in sanitizers else "0"
    afl_env["AFL_USE_UBSAN"] = "1" if "undefined" in sanitizers else "0"

    afl_result = _run(afl_cmd, env=afl_env)
    cov_result = _run(cov_cmd)

    return {
        "ok": afl_result["exit_code"] == 0 and cov_result["exit_code"] == 0,
        "afl_binary_path": str(afl_bin) if afl_result["exit_code"] == 0 else "",
        "cov_binary_path": str(cov_bin) if cov_result["exit_code"] == 0 else "",
        "afl_build_cmd": afl_result["cmd"],
        "cov_build_cmd": cov_result["cmd"],
        "afl_build_log": (afl_result["stdout"] + afl_result["stderr"])[-3000:],
        "cov_build_log": (cov_result["stdout"] + cov_result["stderr"])[-3000:],
        "custom_mutator": custom_mutator_source or "",
    }


# ---------------------------------------------------------------------------
# Running AFL++
# ---------------------------------------------------------------------------

_AFL_STATS_RE = re.compile(r"^([a-z_0-9]+)\s*:\s*(.+)$", re.MULTILINE)


def _read_afl_stats(out_dir: Path) -> dict:
    stats_file = out_dir / "default" / "fuzzer_stats"
    if not stats_file.is_file():
        # Some AFL versions write directly under out_dir
        stats_file = out_dir / "fuzzer_stats"
    if not stats_file.is_file():
        return {}
    text = stats_file.read_text(errors="replace")
    out: dict = {}
    for m in _AFL_STATS_RE.finditer(text):
        out[m.group(1)] = m.group(2).strip()
    return out


@mcp.tool()
def run_afl_for(
    afl_binary_path: Annotated[str, Field(description="Path to the AFL-instrumented binary built by compile_harness")],
    seed_dir: Annotated[str, Field(description="Directory containing seed inputs (will be created if missing; AFL needs at least one seed)")],
    output_dir: Annotated[str, Field(description="afl-fuzz output directory (-o); will be created if missing")],
    seconds: Annotated[int, Field(description="Wall-clock budget for this campaign")] = 30,
    dictionary: Annotated[str, Field(description="Optional path to an AFL dictionary (-x)")] = "",
    stdin_input: Annotated[bool, Field(description="If true, AFL pipes input on stdin (no @@ argument)")] = True,
    extra_args: Annotated[list[str] | None, Field(description="Extra CLI arguments appended after '--' for the target binary, e.g. ['@@']")] = None,
    memory_limit_mb: Annotated[int, Field(description="Memory limit per execution in MB (-m); 0 = unlimited. Used to detect OOM.")] = 1024,
    timeout_ms: Annotated[int, Field(description="Per-execution timeout in milliseconds (-t); 0 = AFL default. Used to detect algorithmic blow-up.")] = 0,
    parallel_workers: Annotated[int, Field(description="Number of AFL workers to run in parallel (1 master + N-1 secondaries sharing the -o dir). 1 = single instance.")] = 1,
) -> dict:
    """Run afl-fuzz for ``seconds`` and parse fuzzer_stats afterwards.

    With ``parallel_workers > 1`` we spawn one master (``-M default``) and
    N-1 secondaries (``-S secondary_<i>``) that share the same ``-o`` output
    directory; AFL then synchronises their queues automatically. Stats are
    summed across workers.
    """
    extra_args = extra_args or []
    afl_fuzz = _which("afl-fuzz")
    if not afl_fuzz:
        return {"ok": False, "error": "afl-fuzz not on PATH (run install_afl.sh)"}
    if not Path(afl_binary_path).is_file():
        return {"ok": False, "error": f"binary not found: {afl_binary_path}"}

    seed_path = Path(seed_dir)
    seed_path.mkdir(parents=True, exist_ok=True)
    if not any(seed_path.iterdir()):
        # AFL refuses to start without at least one seed.
        (seed_path / "seed_0").write_bytes(b"0")

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    if not stdin_input and not extra_args:
        extra_args = ["@@"]

    def _build_cmd(worker_arg: list[str]) -> list[str]:
        cmd = [afl_fuzz, "-i", str(seed_path), "-o", str(out_path), "-V", str(seconds)]
        if memory_limit_mb > 0:
            cmd += ["-m", str(memory_limit_mb)]
        if timeout_ms > 0:
            cmd += ["-t", str(timeout_ms)]
        if dictionary and Path(dictionary).is_file():
            cmd += ["-x", dictionary]
        cmd += worker_arg
        cmd += ["--", afl_binary_path, *extra_args]
        return cmd

    if parallel_workers <= 1:
        cmd = _build_cmd([])
        result = _run(cmd, timeout=seconds + 60, env=AFL_ENV_DEFAULTS)
        results = [result]
        worker_dirs = ["default"]
    else:
        worker_dirs = ["default", *(f"secondary_{i}" for i in range(1, parallel_workers))]
        cmds = [_build_cmd(["-M", "default"])]
        cmds += [_build_cmd(["-S", w]) for w in worker_dirs[1:]]
        # Spawn all in parallel, then wait.
        procs = []
        for c in cmds:
            real_env = {**os.environ, **AFL_ENV_DEFAULTS}
            procs.append(subprocess.Popen(c, env=real_env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE))
        results = []
        for p in procs:
            try:
                _, err = p.communicate(timeout=seconds + 90)
                results.append({"exit_code": p.returncode, "stderr": (err or b"")[-2000:].decode(errors="replace"), "stdout": ""})
            except subprocess.TimeoutExpired:
                p.kill()
                results.append({"exit_code": None, "stderr": "timeout", "stdout": ""})

    # Aggregate stats across worker directories.
    agg = {"execs_per_sec": 0.0, "corpus_count": 0, "saved_crashes": 0, "saved_hangs": 0}
    per_worker_stats: list[dict] = []
    for w in worker_dirs:
        wd = out_path / w
        if not wd.is_dir():
            # Single-instance default lives directly under out_path / "default" or out_path
            wd = out_path
        stats_file = wd / "fuzzer_stats"
        if not stats_file.is_file():
            stats_file = out_path / "default" / "fuzzer_stats"
        if not stats_file.is_file():
            continue
        text = stats_file.read_text(errors="replace")
        wstats = {m.group(1): m.group(2).strip() for m in _AFL_STATS_RE.finditer(text)}
        per_worker_stats.append(wstats)
        try:
            agg["execs_per_sec"] += float(wstats.get("execs_per_sec", "0") or 0)
            agg["corpus_count"] = max(agg["corpus_count"], int(wstats.get("corpus_count", "0") or 0))
            agg["saved_crashes"] = max(agg["saved_crashes"], int(wstats.get("saved_crashes", "0") or 0))
            agg["saved_hangs"] = max(agg["saved_hangs"], int(wstats.get("saved_hangs", "0") or 0))
        except ValueError:
            pass

    # The crashes/queue dirs we report are always the master.
    queue_dir = str(out_path / "default" / "queue")
    crashes_dir = str(out_path / "default" / "crashes")
    hangs_dir = str(out_path / "default" / "hangs")

    return {
        "ok": all(r["exit_code"] == 0 or r["exit_code"] is None for r in results),
        "exit_code": results[0]["exit_code"],
        "stdout_tail": results[0].get("stdout", ""),
        "stderr_tail": results[0].get("stderr", ""),
        "stats": per_worker_stats[0] if per_worker_stats else {},
        "per_worker_stats": per_worker_stats,
        "exec_per_sec": agg["execs_per_sec"],
        "paths_total": agg["corpus_count"],
        "crashes_count": agg["saved_crashes"],
        "hangs_count": agg["saved_hangs"],
        "queue_dir": queue_dir,
        "crashes_dir": crashes_dir,
        "hangs_dir": hangs_dir,
        "output_dir": str(out_path),
        "parallel_workers": parallel_workers,
    }


# ---------------------------------------------------------------------------
# Coverage (llvm-cov first, gcov fallback)
# ---------------------------------------------------------------------------

@mcp.tool()
def run_coverage(
    cov_binary_path: Annotated[str, Field(description="Path to the coverage-instrumented binary built by compile_harness")],
    inputs_dir: Annotated[str, Field(description="Directory of inputs to replay (typically the AFL queue directory)")],
    output_dir: Annotated[str, Field(description="Where to write profraw/profdata/lcov files")],
    stdin_input: Annotated[bool, Field(description="If true, replay each input by piping it on stdin")] = True,
    extra_args: Annotated[list[str] | None, Field(description="Extra CLI args for the binary, e.g. ['@@'] when stdin_input is false")] = None,
    per_input_timeout: Annotated[int, Field(description="Timeout (s) per individual input replay")] = 5,
    max_inputs: Annotated[int, Field(description="Hard cap on inputs to replay (oldest first)")] = 5000,
) -> dict:
    """Replay ``inputs_dir`` against the coverage binary, then export an LCOV file.

    Prefers llvm-cov / llvm-profdata; falls back to gcov+lcov when those tools
    are missing or the binary wasn't built with profile-instr-generate.
    """
    extra_args = extra_args or []
    cov_bin = Path(cov_binary_path)
    if not cov_bin.is_file():
        return {"ok": False, "error": f"binary not found: {cov_binary_path}"}
    in_dir = Path(inputs_dir)
    if not in_dir.is_dir():
        return {"ok": False, "error": f"inputs dir not found: {inputs_dir}"}
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    profraw_dir = out / "profraw"
    profraw_dir.mkdir(exist_ok=True)
    lcov_path = out / "coverage.lcov"

    # Collect inputs (queue files only, skip AFL bookkeeping subdirs).
    inputs = []
    for entry in sorted(in_dir.rglob("*")):
        if entry.is_file() and not entry.name.startswith(".") and entry.name != "fuzzer_stats":
            inputs.append(entry)
            if len(inputs) >= max_inputs:
                break

    replays_ok = 0
    replays_fail = 0
    for i, blob in enumerate(inputs):
        env = {"LLVM_PROFILE_FILE": str(profraw_dir / f"r{i}.profraw")}
        if stdin_input:
            try:
                proc = subprocess.run(
                    [str(cov_bin)], input=blob.read_bytes(), capture_output=True,
                    timeout=per_input_timeout, env={**os.environ, **env},
                )
                replays_ok += 1 if proc.returncode == 0 else 0
                replays_fail += 0 if proc.returncode == 0 else 1
            except subprocess.TimeoutExpired:
                replays_fail += 1
        else:
            args = [str(cov_bin)] + [str(blob) if a == "@@" else a for a in extra_args]
            try:
                proc = subprocess.run(args, capture_output=True, timeout=per_input_timeout,
                                      env={**os.environ, **env})
                replays_ok += 1 if proc.returncode == 0 else 0
                replays_fail += 0 if proc.returncode == 0 else 1
            except subprocess.TimeoutExpired:
                replays_fail += 1

    profdata_path = out / "merged.profdata"
    llvm_profdata = _which("llvm-profdata")
    llvm_cov = _which("llvm-cov")

    if llvm_profdata and llvm_cov:
        merge = _run([llvm_profdata, "merge", "-sparse", "-o", str(profdata_path), str(profraw_dir)])
        if merge["exit_code"] != 0:
            return {"ok": False, "error": "llvm-profdata merge failed", **merge}
        # llvm-cov LCOV output can be many MB — stream straight to the file
        # rather than going through _run() (which truncates stdout).
        try:
            with lcov_path.open("w") as fh:
                proc = subprocess.run(
                    [llvm_cov, "export", "-format=lcov", str(cov_bin),
                     "-instr-profile", str(profdata_path)],
                    stdout=fh, stderr=subprocess.PIPE, text=True, timeout=DEFAULT_TIMEOUT,
                )
        except subprocess.TimeoutExpired:
            return {"ok": False, "error": "llvm-cov export timed out"}
        if proc.returncode != 0:
            return {"ok": False, "error": "llvm-cov export failed", "stderr": proc.stderr[-2000:]}

        # E1: HTML annotated source coverage. Best-effort; non-fatal if it fails.
        html_dir = out / "html"
        html_dir.mkdir(parents=True, exist_ok=True)
        html_path = ""
        try:
            html_proc = subprocess.run(
                [llvm_cov, "show", "-format=html", "-output-dir", str(html_dir),
                 str(cov_bin), "-instr-profile", str(profdata_path)],
                capture_output=True, text=True, timeout=DEFAULT_TIMEOUT,
            )
            index = html_dir / "index.html"
            if html_proc.returncode == 0 and index.is_file():
                html_path = str(index)
        except subprocess.TimeoutExpired:
            html_path = ""
        return {
            "ok": True, "lcov_path": str(lcov_path), "html_path": html_path,
            "inputs_replayed": len(inputs), "replays_ok": replays_ok, "replays_fail": replays_fail,
            "tool": "llvm-cov",
        }

    # Fallback: gcov + lcov
    gcov = _which("gcov")
    lcov_bin = _which("lcov")
    if not (gcov and lcov_bin):
        return {"ok": False, "error": "neither llvm-cov nor lcov is available; run install_afl.sh"}
    base_dir = str(cov_bin.parent)
    capture = _run([lcov_bin, "--capture", "--directory", base_dir, "--output-file", str(lcov_path),
                    "--ignore-errors", "source,gcov,unused"], timeout=DEFAULT_TIMEOUT)
    if capture["exit_code"] != 0:
        return {"ok": False, "error": "lcov capture failed", **capture}
    # E1: genhtml renders LCOV as HTML; non-fatal if missing.
    html_path = ""
    genhtml = _which("genhtml")
    if genhtml:
        html_dir = out / "html"
        html_dir.mkdir(parents=True, exist_ok=True)
        gh = _run([genhtml, "-o", str(html_dir), str(lcov_path),
                   "--ignore-errors", "source"], timeout=DEFAULT_TIMEOUT)
        if gh["exit_code"] == 0 and (html_dir / "index.html").is_file():
            html_path = str(html_dir / "index.html")
    return {
        "ok": True, "lcov_path": str(lcov_path), "html_path": html_path,
        "inputs_replayed": len(inputs), "replays_ok": replays_ok, "replays_fail": replays_fail,
        "tool": "gcov+lcov",
    }


# ---------------------------------------------------------------------------
# Crash triage
# ---------------------------------------------------------------------------

@mcp.tool()
def tmin(
    afl_binary_path: Annotated[str, Field(description="Path to the AFL-instrumented binary")],
    crash_input: Annotated[str, Field(description="Path to the crash input")],
    output_path: Annotated[str, Field(description="Where to write the minimised input")],
    stdin_input: Annotated[bool, Field(description="If true, minimise via stdin (rare; libAFLDriver-based binaries must use file mode)")] = False,
    extra_args: Annotated[list[str] | None, Field(description="Extra CLI args for the binary; '@@' will be replaced with the input path")] = None,
    timeout_seconds: Annotated[int, Field(description="afl-tmin timeout")] = 60,
) -> dict:
    """Run afl-tmin on a crash input.

    By default we use file mode (afl-tmin appends ``@@`` for the input path).
    The libAFLDriver-based AFL binaries built by ``compile_harness`` loop forever
    on stdin in standalone mode, so file mode is the only one that works for
    them.
    """
    extra_args = list(extra_args or [])
    tool = _which("afl-tmin")
    if not tool:
        return {"ok": False, "error": "afl-tmin not on PATH"}
    cmd = [tool, "-i", crash_input, "-o", output_path]
    target_args = extra_args if (stdin_input or "@@" in extra_args) else [*extra_args, "@@"]
    cmd += ["--", afl_binary_path, *target_args]
    result = _run(cmd, timeout=timeout_seconds, env=AFL_ENV_DEFAULTS)
    return {
        "ok": result["exit_code"] == 0,
        "minimized_path": output_path if Path(output_path).is_file() else "",
        "exit_code": result["exit_code"],
        "stderr_tail": result["stderr"],
    }


# Capture from "in " to the next "  /path" (file location) or end of line so
# template args containing spaces (e.g. "std::vector<long, allocator<long>>")
# are kept intact for normalisation.
_ASAN_FRAME_RE = re.compile(
    r"^\s*#\d+\s+0x[0-9a-fA-F]+\s+in\s+(.+?)(?:\s+/|\s*$)",
    re.MULTILINE,
)

# Patterns we strip when normalising symbolised function names so that
# semantically-equivalent stack frames hash to the same key.
_NORMALISE_PATTERNS: list[tuple[re.Pattern, str]] = [
    # std::__1:: -> std::, libc++ inline namespace
    (re.compile(r"std::__\d+::"), "std::"),
    # anonymous namespaces: (anonymous namespace)::foo -> foo
    (re.compile(r"\(anonymous namespace\)::"), ""),
    # numeric suffixes added by clang for inlined/specialised funcs: foo.123 -> foo
    (re.compile(r"(\.\d+)+(?=$|\s)"), ""),
    # cold/lto suffixes
    (re.compile(r"\.(cold|isra|part|constprop)\.\d+"), ""),
]


def _strip_templates(s: str) -> str:
    """Replace every ``<...>`` template-arg block (incl. nested) with ``<>``."""
    out: list[str] = []
    depth = 0
    for c in s:
        if c == "<":
            if depth == 0:
                out.append("<>")
            depth += 1
        elif c == ">":
            depth = max(0, depth - 1)
        elif depth == 0:
            out.append(c)
    return "".join(out)


def _normalise_frame(frame: str) -> str:
    out = _strip_templates(frame)
    for pat, repl in _NORMALISE_PATTERNS:
        out = pat.sub(repl, out)
    return out


def _stack_top_hash(asan_text: str, n: int = 5) -> str:
    """Hash the top N normalised frames of an ASan/UBSan stack trace.

    "Normalised" means address noise, line numbers, template instantiations,
    libc++ inline-namespace markers, anonymous-namespace prefixes, and
    LTO-introduced numeric suffixes have been stripped, so semantically
    identical crashes (e.g. one inlined, one not) produce the same key.
    """
    frames = [_normalise_frame(f) for f in _ASAN_FRAME_RE.findall(asan_text)[:n]]
    if not frames:
        return ""
    h = hashlib.sha256(("|".join(frames)).encode()).hexdigest()
    return h[:16]


# ---------------------------------------------------------------------------
# Corpus minimisation (afl-cmin) and dictionary extraction
# ---------------------------------------------------------------------------

@mcp.tool()
def cmin(
    afl_binary_path: Annotated[str, Field(description="Path to the AFL-instrumented binary")],
    input_dir: Annotated[str, Field(description="Directory of inputs to minimise (e.g. <run>/default/queue)")],
    output_dir: Annotated[str, Field(description="Directory where the minimised corpus will be written")],
    stdin_input: Annotated[bool, Field(description="If true, drive via stdin (default for libAFLDriver-style binaries is false)")] = False,
    extra_args: Annotated[list[str] | None, Field(description="Extra CLI args; '@@' replaced with input path")] = None,
    timeout_seconds: Annotated[int, Field(description="Total afl-cmin timeout")] = 300,
) -> dict:
    """Minimise a corpus with ``afl-cmin`` (drops inputs that don't add coverage)."""
    extra_args = list(extra_args or [])
    tool = _which("afl-cmin")
    if not tool:
        return {"ok": False, "error": "afl-cmin not on PATH"}
    if not Path(afl_binary_path).is_file():
        return {"ok": False, "error": f"binary not found: {afl_binary_path}"}
    if not Path(input_dir).is_dir():
        return {"ok": False, "error": f"input dir not found: {input_dir}"}
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    target_args = extra_args if (stdin_input or "@@" in extra_args) else [*extra_args, "@@"]
    cmd = [tool, "-i", input_dir, "-o", output_dir, "--", afl_binary_path, *target_args]
    result = _run(cmd, timeout=timeout_seconds, env=AFL_ENV_DEFAULTS)
    in_count = sum(1 for _ in Path(input_dir).rglob("*") if _.is_file())
    out_count = sum(1 for _ in Path(output_dir).rglob("*") if _.is_file())
    return {
        "ok": result["exit_code"] == 0 and out_count > 0,
        "input_count": in_count,
        "minimised_count": out_count,
        "exit_code": result["exit_code"],
        "stderr_tail": result["stderr"],
    }


_PRINTABLE_RE = re.compile(rb"[ -~]{4,32}")


@mcp.tool()
def extract_dictionary(
    binary_path: Annotated[str, Field(description="Path to a binary or object file to mine for printable strings")],
    output_path: Annotated[str, Field(description="Where to write the AFL dictionary file")],
    min_length: Annotated[int, Field(description="Minimum string length to include")] = 4,
    max_length: Annotated[int, Field(description="Maximum string length to include")] = 32,
    max_entries: Annotated[int, Field(description="Cap on dictionary size to keep AFL fast")] = 256,
) -> dict:
    """Extract printable substrings from a binary as an AFL dictionary.

    Heuristic: scan for ASCII runs between ``min_length`` and ``max_length``,
    drop common library noise (compiler banners, ELF section names, file
    paths), keep the rest. Result is written in AFL ``-x`` dictionary format.
    """
    src = Path(binary_path)
    if not src.is_file():
        return {"ok": False, "error": f"binary not found: {binary_path}"}
    data = src.read_bytes()
    seen: set[bytes] = set()
    skip_substrings = (
        b"GCC:", b"clang version", b"GLIBC_", b".text", b".rodata", b".data",
        b".bss", b".init", b".fini", b"/usr/", b"/home/", b"/tmp/", b"/lib",
        b"AddressSanitizer", b"UndefinedBehavior", b"libstdc++", b"libc.so",
    )
    for m in _PRINTABLE_RE.finditer(data):
        s = m.group(0)
        if len(s) < min_length or len(s) > max_length:
            continue
        if any(skip in s for skip in skip_substrings):
            continue
        # Drop strings that look like file paths or symbol mangling
        if s.startswith(b"_Z") or s.startswith(b"/"):
            continue
        seen.add(s)
        if len(seen) >= max_entries:
            break
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as fh:
        fh.write("# AFL dictionary auto-extracted by fuzz_runner.extract_dictionary\n")
        for i, s in enumerate(sorted(seen)):
            escaped = "".join(
                f"\\x{b:02x}" if (b < 0x20 or b >= 0x7f or b in b'"\\') else chr(b) for b in s
            )
            fh.write(f'kw{i}="{escaped}"\n')
    return {"ok": True, "dictionary_path": str(out), "entries": len(seen)}


# ---------------------------------------------------------------------------
# Reproducer artefact bundling
# ---------------------------------------------------------------------------

@mcp.tool()
def package_reproducer(
    output_path: Annotated[str, Field(description="Where to write the .tgz reproducer bundle")],
    minimised_input: Annotated[str, Field(description="Path to the minimised crash input")],
    harness_source: Annotated[str, Field(description="Path to the harness .c/.cc file")],
    afl_binary_path: Annotated[str, Field(description="Absolute path of the AFL-instrumented binary that crashed")] = "",
    build_cmd_afl: Annotated[str, Field(description="Build command used to produce the AFL binary (for the README)")] = "",
    sanitizer_output: Annotated[str, Field(description="Trimmed sanitiser output to embed in the README")] = "",
    classification: Annotated[str, Field(description="Short crash classification text for the README")] = "",
) -> dict:
    """Bundle a single-crash reproducer as a .tgz: minimised input + harness +
    build command + a README explaining how to reproduce. Mirrors OSS-Fuzz's
    download-reproducer artefact."""
    inp = Path(minimised_input)
    src = Path(harness_source)
    if not inp.is_file():
        return {"ok": False, "error": f"minimised input not found: {minimised_input}"}
    if not src.is_file():
        return {"ok": False, "error": f"harness source not found: {harness_source}"}
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    readme = (
        "# Reproducer\n\n"
        f"Classification: {classification or '(not set)'}\n\n"
        f"AFL binary path (when archive was built): {afl_binary_path or '(not set)'}\n\n"
        "## Reproduce\n\n"
        "```bash\n"
        "tar xzf reproducer.tgz\n"
        f"# Build (if you don't have the AFL binary):\n"
        f"# {build_cmd_afl or '<see fuzz_context.harness.build_cmd_afl>'}\n"
        "# Run the minimised input through the binary in argv mode:\n"
        "ASAN_OPTIONS=abort_on_error=0:halt_on_error=1:print_stacktrace=1:detect_leaks=0 \\\n"
        "  ./<harness_basename>.afl input.bin\n"
        "```\n\n"
        "## Sanitiser output (truncated)\n\n"
        "```\n" + (sanitizer_output[:4000] if sanitizer_output else "(not captured)") + "\n```\n"
    )
    with tarfile.open(out, "w:gz") as tar:
        tar.add(inp, arcname="input.bin")
        tar.add(src, arcname=src.name)
        info = tarfile.TarInfo(name="README.md")
        readme_bytes = readme.encode()
        info.size = len(readme_bytes)
        tar.addfile(info, io.BytesIO(readme_bytes))
    return {"ok": True, "reproducer_path": str(out), "size_bytes": out.stat().st_size}


@mcp.tool()
def replay_under_asan(
    afl_binary_path: Annotated[str, Field(description="Path to the AFL+ASan-instrumented binary")],
    input_path: Annotated[str, Field(description="Input that triggers a crash")],
    stdin_input: Annotated[bool, Field(description="If true, feed input via stdin (rare; libAFLDriver-based binaries must use file mode)")] = False,
    extra_args: Annotated[list[str] | None, Field(description="Extra CLI args for the binary; '@@' will be replaced with the input path")] = None,
    timeout_seconds: Annotated[int, Field(description="Run timeout")] = 30,
) -> dict:
    """Replay a single input and capture the sanitiser report. Returns stack_top_hash.

    Defaults to file mode (input passed as argv) because libAFLDriver-based
    AFL binaries loop forever on stdin in standalone mode.
    """
    extra_args = list(extra_args or [])
    if not Path(afl_binary_path).is_file():
        return {"ok": False, "error": f"binary not found: {afl_binary_path}"}
    env = {**AFL_ENV_DEFAULTS, "ASAN_OPTIONS": "abort_on_error=0:halt_on_error=1:print_stacktrace=1:detect_leaks=0"}
    if stdin_input:
        try:
            proc = subprocess.run(
                [afl_binary_path], input=Path(input_path).read_bytes(),
                capture_output=True, timeout=timeout_seconds, env={**os.environ, **env},
            )
            output = (proc.stdout.decode(errors="replace") + proc.stderr.decode(errors="replace"))
            rc = proc.returncode
        except subprocess.TimeoutExpired:
            return {"ok": False, "timed_out": True}
    else:
        if extra_args:
            args = [afl_binary_path] + [input_path if a == "@@" else a for a in extra_args]
        else:
            args = [afl_binary_path, input_path]
        try:
            proc = subprocess.run(args, capture_output=True, timeout=timeout_seconds,
                                  env={**os.environ, **env})
            output = (proc.stdout.decode(errors="replace") + proc.stderr.decode(errors="replace"))
            rc = proc.returncode
        except subprocess.TimeoutExpired:
            return {"ok": False, "timed_out": True}
    sig = ""
    m = re.search(r"AddressSanitizer:\s*([^\n]+)", output) or re.search(r"runtime error:\s*([^\n]+)", output)
    if m:
        sig = m.group(1).strip()
    return {
        "ok": True,
        "exit_code": rc,
        "crashed": rc != 0 or bool(sig),
        "sanitizer_signature": sig,
        "stack_top_hash": _stack_top_hash(output),
        "sanitizer_output": output[-6000:],
    }


# ---------------------------------------------------------------------------
# Static call graph + reachability (E3 — Fuzz-Introspector lite)
# ---------------------------------------------------------------------------

@mcp.tool()
def build_call_graph(
    source_root: Annotated[str, Field(description="Path to the unpacked source tree (e.g. the repo root)")],
    cov_lcov_path: Annotated[str, Field(description="Optional LCOV tracefile to mark which functions were reached")] = "",
    output_dot: Annotated[str, Field(description="Where to write the Graphviz .dot file")] = "",
    output_svg: Annotated[str, Field(description="Where to write the rendered SVG (requires graphviz dot on PATH)")] = "",
    max_nodes: Annotated[int, Field(description="Hard cap on functions to include (largest reachable subgraph wins)")] = 200,
) -> dict:
    """Build a static call graph using ``ctags`` + ``cscope`` and annotate with
    coverage. This is a lightweight Fuzz-Introspector-style tool that lets the
    agent (and the dashboard) see which library functions the harness chain
    actually reaches versus which remain untouched.

    Output: a Graphviz ``.dot`` file (and SVG, if ``dot`` is installed) where:
      - reached functions are coloured green
      - unreached functions are coloured red
      - external library calls (functions defined elsewhere) are grey
    """
    root = Path(source_root)
    if not root.is_dir():
        return {"ok": False, "error": f"source_root not found: {source_root}"}

    ctags = _which("ctags")
    cscope = _which("cscope")
    if not ctags or not cscope:
        return {"ok": False, "error": "ctags and cscope are required (install_afl.sh installs them)"}

    # 1. Build a tags database for function definitions.
    tags_file = root / "_callgraph_tags"
    _run([ctags, "-R", "--c-kinds=fp", "--fields=+ne", "--languages=C,C++",
          "-f", str(tags_file), str(root)], timeout=DEFAULT_TIMEOUT)
    if not tags_file.is_file():
        return {"ok": False, "error": "ctags failed to produce a tags file"}

    # Parse function definitions (kind 'f') from the ctags file.
    func_defs: dict[str, str] = {}
    for line in tags_file.read_text(errors="replace").splitlines():
        if line.startswith("!"):
            continue
        parts = line.split("\t")
        if len(parts) < 4:
            continue
        name, file_, _addr = parts[0], parts[1], parts[2]
        kind = parts[3].split(";")[0]
        if kind == "f":
            func_defs.setdefault(name, file_)

    # 2. Build cscope database for call relationships.
    cscope_files = root / "_callgraph_files"
    file_list = []
    for ext in ("c", "cc", "cpp", "h", "hpp"):
        file_list.extend(str(p) for p in root.rglob(f"*.{ext}"))
    cscope_files.write_text("\n".join(file_list))
    _run([cscope, "-q", "-b", "-k", "-i", str(cscope_files),
          "-f", str(root / "_callgraph_cscope.out")], timeout=DEFAULT_TIMEOUT * 2)

    # 3. For each known function, query "who does this call?"
    callgraph: dict[str, set[str]] = {}
    for name in list(func_defs.keys())[:max_nodes]:
        result = _run([cscope, "-d", "-L", "-2", name,
                       "-f", str(root / "_callgraph_cscope.out")], timeout=30)
        callees: set[str] = set()
        for ln in (result.get("stdout") or "").splitlines():
            # cscope -L -2 output: <file> <function> <line> <text>
            toks = ln.split()
            if len(toks) >= 4:
                callees.add(toks[1])
        callgraph[name] = callees

    # 4. Cross-reference with coverage to find reached functions.
    reached: set[str] = set()
    if cov_lcov_path and Path(cov_lcov_path).is_file():
        for raw in Path(cov_lcov_path).read_text(errors="replace").splitlines():
            if raw.startswith("FNDA:"):
                try:
                    hits_str, name = raw[5:].split(",", 1)
                    if int(hits_str) > 0:
                        reached.add(name)
                except ValueError:
                    pass

    # 5. Emit dot.
    dot_path = Path(output_dot) if output_dot else (root / "_callgraph.dot")
    lines = ["digraph callgraph {", '  rankdir=LR;', '  node [shape=box, fontsize=10, style=filled];']
    nodes_emitted: set[str] = set()
    for fn, callees in callgraph.items():
        nodes_emitted.add(fn)
        nodes_emitted.update(callees)
        for c in callees:
            lines.append(f'  "{fn}" -> "{c}";')
    for fn in nodes_emitted:
        if fn in reached:
            color = "#bdf7bd"  # reached
        elif fn in func_defs:
            color = "#f7bdbd"  # known but unreached
        else:
            color = "#dddddd"  # external
        lines.append(f'  "{fn}" [fillcolor="{color}"];')
    lines.append("}")
    dot_path.write_text("\n".join(lines))

    # 6. Render to SVG if dot is available.
    svg_path = Path(output_svg) if output_svg else dot_path.with_suffix(".svg")
    rendered = ""
    dot_bin = _which("dot")
    if dot_bin:
        r = _run([dot_bin, "-Tsvg", str(dot_path), "-o", str(svg_path)], timeout=DEFAULT_TIMEOUT)
        if r["exit_code"] == 0 and svg_path.is_file():
            rendered = str(svg_path)

    return {
        "ok": True,
        "dot_path": str(dot_path),
        "svg_path": rendered,
        "functions_total": len(func_defs),
        "functions_in_graph": len(callgraph),
        "functions_reached": len(reached & nodes_emitted),
        "functions_unreached": len(nodes_emitted) - len(reached & nodes_emitted),
        # Convenience: the unreached set, sorted, capped to a sensible size
        # for downstream consumers (vuln reports, dashboards).
        "unreached_function_names": sorted(
            (nodes_emitted & set(func_defs.keys())) - reached
        )[:max_nodes],
    }


# ---------------------------------------------------------------------------
# E3: untouched API surface (Fuzz-Introspector-style)
# ---------------------------------------------------------------------------

# Heuristic for "public-API function" names. Anything starting with one of
# these prefixes (after stripping leading underscores) is treated as public.
# This is intentionally broad so we don't miss anything; the agent can
# narrow further via the `extern_only_headers` argument.
_PUBLIC_PREFIX_HINTS = (
    # Common library naming conventions
    "lzma_", "json_", "cJSON_", "XML_", "expat_", "onig_", "regex_",
    "ssl_", "tls_", "crypto_", "ec_", "rsa_", "evp_", "x509_",
    "png_", "jpeg_", "tiff_", "gif_",
    "av_", "avformat_", "avcodec_",
    "sqlite3_", "pcre_", "pcre2_",
    # Generic catch-all for "looks public"
)


@mcp.tool()
def untouched_api_surface(
    source_root: Annotated[str, Field(description="Path to the unpacked source tree (e.g. the repo root)")],
    reached_function_names: Annotated[list[str], Field(description="Function names already reached by any fuzzing run (use get_repo_reached_functions on fuzz_context for the full set)")],
    extern_only_headers: Annotated[list[str] | None, Field(description="Optional list of glob patterns for public-API headers (e.g. ['include/**/*.h']); when set, only function declarations from these headers are considered public")] = None,
    max_results: Annotated[int, Field(description="Cap on the number of unreached function names to return")] = 200,
) -> dict:
    """Compute the set of public-API functions that no fuzzing run has reached.

    Two strategies, run together and unioned:
      1. ctags --c-kinds=p (function prototypes) restricted to ``extern_only_headers``
         globs. This is the strict / "documented public API" set.
      2. ctags --c-kinds=f (function definitions) filtered by name prefix
         (heuristic: starts with one of a small set of common library prefixes).
         This catches public functions that don't have a separate prototype in
         a public header but follow naming conventions.

    Returns the never-reached subset, sorted by name, capped at ``max_results``.
    """
    root = Path(source_root)
    if not root.is_dir():
        return {"ok": False, "error": f"source_root not found: {source_root}"}

    ctags = _which("ctags")
    if not ctags:
        return {"ok": False, "error": "ctags is required (install_afl.sh installs universal-ctags)"}

    public_funcs: set[str] = set()

    # Strategy 1: prototypes from public headers.
    if extern_only_headers:
        header_files: list[str] = []
        for pat in extern_only_headers:
            header_files.extend(_glob.glob(str(root / pat), recursive=True))
        if header_files:
            tags_file = root / "_untouched_tags_p"
            _run([ctags, "--c-kinds=p", "--fields=+ne", "--languages=C,C++",
                  "-f", str(tags_file), *header_files], timeout=DEFAULT_TIMEOUT)
            if tags_file.is_file():
                for line in tags_file.read_text(errors="replace").splitlines():
                    if line.startswith("!"):
                        continue
                    name = line.split("\t", 1)[0]
                    if name and not name.startswith("_"):
                        public_funcs.add(name)

    # Strategy 2: definitions whose name starts with a known prefix.
    tags_file = root / "_untouched_tags_f"
    _run([ctags, "-R", "--c-kinds=f", "--fields=+ne", "--languages=C,C++",
          "-f", str(tags_file), str(root)], timeout=DEFAULT_TIMEOUT)
    all_defs: set[str] = set()
    if tags_file.is_file():
        for line in tags_file.read_text(errors="replace").splitlines():
            if line.startswith("!"):
                continue
            name = line.split("\t", 1)[0]
            if name and not name.startswith("_"):
                all_defs.add(name)
                if any(name.startswith(p) for p in _PUBLIC_PREFIX_HINTS):
                    public_funcs.add(name)

    reached = set(reached_function_names or [])
    untouched = sorted(public_funcs - reached)
    return {
        "ok": True,
        "public_total": len(public_funcs),
        "reached_total": len(reached & public_funcs),
        "untouched_total": len(untouched),
        "untouched": untouched[:max_results],
        "definitions_total": len(all_defs),
    }


# ---------------------------------------------------------------------------
# Workspace helpers
# ---------------------------------------------------------------------------

@mcp.tool()
def workspace_paths() -> dict:
    """Return the paths the agent should write harness sources, seeds, builds and runs into."""
    return {
        "builds_dir": str(FUZZ_BUILDS),
        "runs_dir": str(FUZZ_RUNS),
        "workspace_dir": str(WORKSPACE),
        "format_assets_dir": str(_FORMAT_ASSETS_DIR),
        "persistent_corpus_root": str(PERSISTENT_CORPUS),
    }


# v8: persistent corpus dir (one per harness id). Survives across campaigns
# so AFL's queue from yesterday's run becomes today's seed corpus.
PERSISTENT_CORPUS = WORKSPACE / "corpus"
PERSISTENT_CORPUS.mkdir(parents=True, exist_ok=True)


@mcp.tool()
def get_persistent_corpus_dir(
    harness_id: Annotated[int, Field(description="Stable harness id from fuzz_context.get_harnesses")],
) -> dict:
    """Return the persistent corpus directory for a harness, creating it if
    needed and seeding it with one minimal input if empty so AFL won't refuse
    to start.

    Use this as the ``seed_dir`` for ``run_afl_for`` and as the ``output_dir``
    of an end-of-iteration ``cmin`` step. The same path is reused across
    campaigns; AFL will pick up yesterday's queue automatically.
    """
    p = PERSISTENT_CORPUS / f"harness_{harness_id}"
    p.mkdir(parents=True, exist_ok=True)
    if not any(p.iterdir()):
        # AFL refuses to start with an empty seed dir.
        (p / "seed_0").write_bytes(b"0")
    return {
        "ok": True,
        "corpus_dir": str(p),
        "input_count": sum(1 for _ in p.iterdir() if _.is_file()),
    }


@mcp.tool()
def fold_queue_into_persistent_corpus(
    afl_binary_path: Annotated[str, Field(description="Path to the AFL-instrumented binary built by compile_harness")],
    queue_dir: Annotated[str, Field(description="AFL's per-iteration queue directory (run_dir/default/queue)")],
    persistent_corpus_dir: Annotated[str, Field(description="The persistent corpus dir from get_persistent_corpus_dir")],
    timeout_seconds: Annotated[int, Field(description="Total afl-cmin timeout")] = 300,
) -> dict:
    """Merge AFL's iteration queue into the persistent corpus, then minimise.

    Two-pass:
      1. Copy every queue file into ``persistent_corpus_dir`` (fast).
      2. ``afl-cmin`` the persistent corpus in place: drops inputs that don't
         add coverage, so the corpus can never grow without bound.

    Returns counts of {merged_in, after_cmin}. Idempotent on the queue side
    (filenames are content-addressed by AFL).
    """
    qd = Path(queue_dir)
    cd = Path(persistent_corpus_dir)
    if not Path(afl_binary_path).is_file():
        return {"ok": False, "error": f"binary not found: {afl_binary_path}"}
    if not qd.is_dir():
        return {"ok": False, "error": f"queue not found: {queue_dir}"}
    cd.mkdir(parents=True, exist_ok=True)

    before = sum(1 for _ in cd.iterdir() if _.is_file())
    merged = 0
    for src_path in qd.iterdir():
        if not src_path.is_file() or src_path.name.startswith("."):
            continue
        if src_path.name in {"fuzzer_stats", "README.txt"}:
            continue
        dst = cd / src_path.name
        if dst.exists():
            continue
        try:
            dst.write_bytes(src_path.read_bytes())
            merged += 1
        except OSError:
            continue

    # Now cmin the persistent corpus into a temp dir and atomically swap.
    tmp = cd.with_suffix(".cmin")
    if tmp.exists():
        shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir(parents=True, exist_ok=True)
    cmin_result = cmin.fn(
        afl_binary_path=afl_binary_path,
        input_dir=str(cd),
        output_dir=str(tmp),
        timeout_seconds=timeout_seconds,
    )
    if cmin_result.get("ok") and (cmin_result.get("minimised_count") or 0) > 0:
        # Replace the persistent corpus with the minimised one.
        shutil.rmtree(cd)
        tmp.rename(cd)
        after = sum(1 for _ in cd.iterdir() if _.is_file())
    else:
        # cmin failed; keep what we had merged.
        shutil.rmtree(tmp, ignore_errors=True)
        after = sum(1 for _ in cd.iterdir() if _.is_file())
    return {
        "ok": True, "before": before, "merged_in": merged, "after_cmin": after,
        "cmin_result": cmin_result,
    }


# ---------------------------------------------------------------------------
# v8 — F4: confirm previously-known crashes still reproduce
# ---------------------------------------------------------------------------

@mcp.tool()
def reproduce_crash(
    afl_binary_path: Annotated[str, Field(description="Path to the AFL+ASan-instrumented binary")],
    input_path: Annotated[str, Field(description="Crash input path (typically the minimised one)")],
    timeout_seconds: Annotated[int, Field(description="Per-attempt timeout")] = 30,
) -> dict:
    """Run a crash input through the AFL binary in argv mode and report whether
    it still crashes. Lighter wrapper around ``replay_under_asan``: returns a
    boolean ``crashed`` plus the new ``stack_top_hash`` for verification.

    Used by ``confirm_fixed_crashes`` workflows in the agent prompt: if a
    previously-crashing input no longer crashes, the agent calls
    ``update_crash_verdict(... verdict="fixed" ...)``.
    """
    if not Path(afl_binary_path).is_file():
        return {"ok": False, "error": f"binary not found: {afl_binary_path}"}
    if not Path(input_path).is_file():
        return {"ok": False, "error": f"input not found: {input_path}"}
    return replay_under_asan.fn(
        afl_binary_path=afl_binary_path, input_path=input_path,
        stdin_input=False, timeout_seconds=timeout_seconds,
    )


# ---------------------------------------------------------------------------
# C5: structure-aware fuzzing — format dictionaries + custom mutators
# ---------------------------------------------------------------------------

# Pre-built format assets ship with the package under
# src/seclab_taskflows/dictionaries/. We resolve the absolute path at import.
_FORMAT_ASSETS_DIR = Path(__file__).parent.parent / "dictionaries"

_FORMAT_ASSETS = {
    "json": {
        "dictionary": "json.dict",
        "mutator": "json_mutator.c",
        "description": "JSON / JSON-Lines parsers (cJSON, jansson, json-c, ...)",
    },
    "xml": {
        "dictionary": "xml.dict",
        "mutator": "xml_mutator.c",
        "description": "XML / SAX-style parsers (libexpat, libxml2, ...)",
    },
    "regex": {
        "dictionary": "regex.dict",
        "mutator": "regex_mutator.c",
        "description": "Regex pattern compilers (PCRE, Oniguruma, RE2, ...)",
    },
    "binary_tlv": {
        "dictionary": None,
        "mutator": "binary_tlv_mutator.c",
        "description": (
            "Length-prefixed binary records (PNG chunks, ELF sections, "
            "MP4 boxes, network protocol frames). Assumes <u32_be length><bytes>."
        ),
    },
    "png": {
        "dictionary": "png.dict",
        "mutator": "binary_tlv_mutator.c",
        "description": (
            "PNG decoders (libpng, lodepng, ...). PNG chunks already use a "
            "u32-big-endian length prefix so the binary_tlv mutator works."
        ),
    },
}


@mcp.tool()
def list_format_assets() -> dict:
    """List the format-specific dictionaries and custom mutators that ship
    with the fuzzing taskflow."""
    out = {}
    for name, spec in _FORMAT_ASSETS.items():
        dict_path = _FORMAT_ASSETS_DIR / spec["dictionary"] if spec.get("dictionary") else None
        mut_path = _FORMAT_ASSETS_DIR / spec["mutator"] if spec.get("mutator") else None
        out[name] = {
            "description": spec["description"],
            "dictionary_path": str(dict_path) if dict_path and dict_path.is_file() else "",
            "mutator_source_path": str(mut_path) if mut_path and mut_path.is_file() else "",
        }
    return out


@mcp.tool()
def get_format_dictionary(
    format_name: Annotated[str, Field(description="One of: json, xml, regex, png. Returns the absolute path to the AFL dictionary file shipped with the taskflow.")],
    output_path: Annotated[str, Field(description="Optional: copy the dictionary to this path (e.g. into the harness's seeds dir). Empty string = don't copy, just return the source path.")] = "",
) -> dict:
    """Return the path to a pre-built per-format AFL dictionary.

    Pass the result to ``run_afl_for(..., dictionary=<path>)``. Combine with
    ``write_format_mutator`` for full structure-aware fuzzing.
    """
    spec = _FORMAT_ASSETS.get(format_name.lower())
    if not spec or not spec.get("dictionary"):
        return {"ok": False, "error": f"no dictionary for format '{format_name}'; known: {sorted(k for k, v in _FORMAT_ASSETS.items() if v.get('dictionary'))}"}
    src = _FORMAT_ASSETS_DIR / spec["dictionary"]
    if not src.is_file():
        return {"ok": False, "error": f"dictionary file missing: {src}"}
    if output_path:
        dst = Path(output_path)
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(src.read_bytes())
        return {"ok": True, "dictionary_path": str(dst), "source": str(src), "entries_estimated": _count_dict_entries(src)}
    return {"ok": True, "dictionary_path": str(src), "entries_estimated": _count_dict_entries(src)}


def _count_dict_entries(p: Path) -> int:
    try:
        return sum(1 for line in p.read_text(errors="replace").splitlines()
                   if line and not line.lstrip().startswith("#") and "=" in line)
    except OSError:
        return 0


@mcp.tool()
def write_format_mutator(
    format_name: Annotated[str, Field(description="One of: json, xml, regex, binary_tlv, png. Returns a structure-aware LLVMFuzzerCustomMutator C file.")],
    output_path: Annotated[str, Field(description="Where to write the mutator .c file (typically alongside the harness)")],
) -> dict:
    """Materialise a structure-aware libFuzzer/AFL++ custom mutator for a known
    format. Pass the resulting path to ``compile_harness(..., custom_mutator_source=<path>)``.

    The mutators ship as part of this package; this tool just copies the right
    file into the harness directory so the taskflow's build step can find it.
    """
    spec = _FORMAT_ASSETS.get(format_name.lower())
    if not spec or not spec.get("mutator"):
        return {"ok": False, "error": f"no mutator for format '{format_name}'; known: {sorted(_FORMAT_ASSETS.keys())}"}
    src = _FORMAT_ASSETS_DIR / spec["mutator"]
    if not src.is_file():
        return {"ok": False, "error": f"mutator file missing: {src}"}
    dst = Path(output_path)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(src.read_text())
    return {
        "ok": True,
        "mutator_source_path": str(dst),
        "format_name": format_name.lower(),
        "description": spec["description"],
    }


# ---------------------------------------------------------------------------
# Source-aware (project-specific) mutator generation
# ---------------------------------------------------------------------------

# Skip these directory names when walking the source tree — almost always
# noise (test fixtures, generated code, vendored deps).
_SOURCE_SKIP_DIRS = frozenset({
    ".git", ".github", "tests", "test", "examples", "example", "docs",
    "doc", "bench", "benchmarks", "fuzz", "fuzzers", "fuzzing", "vendor",
    "third_party", "thirdparty", "build", "out", "node_modules", ".venv",
})

# Numeric values to drop — too generic to give the fuzzer signal.
_NUMERIC_NOISE = frozenset({
    0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 16, 32, 64, 100, 128, 200, 256,
    0xff, 0xffff, 0xffffffff, 0x1000, 0x10000,
})

_STRING_LITERAL_RE = re.compile(r'"((?:[^"\\\n]|\\.){2,128})"')
_DEFINE_NUM_RE = re.compile(
    r'#\s*define\s+\w+\s*\(?\s*(0x[0-9a-fA-F]+|-?\d+)(?:[uUlL]+)?\s*\)?\s*(?:$|/\*|//)',
    re.MULTILINE,
)
_CASE_NUM_RE = re.compile(r'\bcase\s+(0x[0-9a-fA-F]+|-?\d+)(?:[uUlL]+)?\s*:')
_ENUM_NUM_RE = re.compile(r'\b\w+\s*=\s*(0x[0-9a-fA-F]+|-?\d+)(?:[uUlL]+)?\s*[,\}]')


def _extract_project_tokens(
    source_root: Path,
    max_files: int = 800,
    max_strings: int = 192,
    max_constants: int = 96,
    max_string_len: int = 64,
) -> dict:
    """Walk a C/C++ source tree, extract project-specific tokens for fuzzing.

    Returns a dict with:
      strings:   most frequent printable-ASCII string literals
      constants: most frequent magic-looking integer constants (defines,
                 switch cases, enum values), as 32-bit unsigned ints
      stats:     debugging info (files scanned, raw counts before dedup)
    """
    if not source_root.is_dir():
        return {"strings": [], "constants": [], "stats": {"error": "not a directory"}}

    files: list[Path] = []
    for fp in source_root.rglob("*"):
        if not fp.is_file():
            continue
        if fp.suffix.lower() not in (".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".hxx"):
            continue
        # Skip files under any noise directory anywhere in the path.
        if any(part.lower() in _SOURCE_SKIP_DIRS for part in fp.relative_to(source_root).parts):
            continue
        files.append(fp)
        if len(files) >= max_files:
            break

    strings_seen: dict[str, int] = {}
    constants_seen: dict[int, int] = {}

    # Patterns we drop because they're build-system / printf-format noise
    # rather than real protocol tokens. These checks are heuristic and
    # intentionally conservative.
    header_suffixes = (".h", ".hpp", ".hxx", ".hh", ".inc")
    inttypes_macro_re = re.compile(r"\bPRI[diouxX]\w*\b")
    # Inline-asm constraint strings: "=r", "+r", "=&r", "+&r", "=&q,m", ...
    asm_constraint_re = re.compile(r"^[=+&%~][=+&%~]?[a-zA-Z][a-zA-Z,]?$")
    # Snippets from license/copyright boilerplate that appear in every C file.
    license_phrases = (
        "License", "license", "AS IS", "Software", "Copyright", "copyright",
        "WARRANTY", "warranty", "PURPOSE", "MERCHANTABILITY",
        "REDISTRIBUTION", "this software", "spdx", "SPDX",
    )

    for fp in files:
        try:
            text = fp.read_text(errors="replace")
        except OSError:
            continue

        # Strings: pure printable ASCII only (avoids C-escape-emission ambiguity
        # and keeps tokens small enough to splice without ballooning input).
        for m in _STRING_LITERAL_RE.finditer(text):
            raw = m.group(1)
            # Decode common escapes for length filtering.
            decoded = raw.encode("utf-8", errors="replace").decode("unicode_escape", errors="replace")
            if len(decoded) < 3 or len(decoded) > max_string_len:
                continue
            if not all(0x20 <= ord(c) <= 0x7e for c in decoded):
                continue
            stripped = decoded.strip()
            if not stripped:
                continue
            # Drop file paths.
            if decoded.startswith(("/", "./", "../")):
                continue
            # Drop header names (`#include "foo.h"`).
            low = decoded.lower()
            if low.endswith(header_suffixes):
                continue
            # Drop ABI / inttypes format-macro fragments (PRIu32 etc.).
            if inttypes_macro_re.search(decoded):
                continue
            # Drop inline-asm constraint strings ("=r", "+&r", "%eax", etc.).
            if asm_constraint_re.match(decoded):
                continue
            # Drop compiler-flag-looking strings ("-Wformat", "-fPIC", ...).
            if decoded.startswith("-") and len(decoded) <= 24:
                continue
            # Drop license / copyright boilerplate that ships with every file.
            if any(phrase in decoded for phrase in license_phrases):
                continue
            # Drop strings that are mostly punctuation / format directives.
            # A real protocol token has at least three alphabetic chars.
            alpha_count = sum(1 for c in decoded if c.isalpha())
            if alpha_count < 3:
                continue
            # Drop pure numbers.
            try:
                float(stripped)
                continue
            except ValueError:
                pass
            strings_seen[decoded] = strings_seen.get(decoded, 0) + 1

        for regex in (_DEFINE_NUM_RE, _CASE_NUM_RE, _ENUM_NUM_RE):
            for m in regex.finditer(text):
                try:
                    v = int(m.group(1), 0) & 0xFFFFFFFF
                except (ValueError, OverflowError):
                    continue
                if v in _NUMERIC_NOISE:
                    continue
                constants_seen[v] = constants_seen.get(v, 0) + 1

    # Top-N by frequency, ties broken by lexical order for determinism.
    top_strings = [
        s for s, _ in sorted(strings_seen.items(), key=lambda kv: (-kv[1], kv[0]))[:max_strings]
    ]
    top_constants = [
        c for c, _ in sorted(constants_seen.items(), key=lambda kv: (-kv[1], kv[0]))[:max_constants]
    ]
    return {
        "strings": top_strings,
        "constants": top_constants,
        "stats": {
            "files_scanned": len(files),
            "strings_total_distinct": len(strings_seen),
            "constants_total_distinct": len(constants_seen),
            "max_strings": max_strings,
            "max_constants": max_constants,
        },
    }


def _c_string_escape(s: str) -> str:
    """Escape a Python string for safe embedding in a C string literal.

    Inserts a "" terminator + "" (string concatenation) when emitting hex
    escapes that would otherwise greedy-eat the next ASCII hex digit.
    """
    out: list[str] = []
    for ch in s:
        b = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= b <= 0x7E:
            out.append(ch)
        elif b == 0x09:
            out.append("\\t")
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        else:
            # We filter to printable ASCII upstream so this branch is rarely
            # taken; emit a 3-digit octal escape (unambiguous re. neighbours).
            out.append(f"\\{b:03o}")
    return "".join(out)


_SMART_MUTATOR_TEMPLATE = """\
/* AUTO-GENERATED by fuzz_runner.generate_smart_mutator
 * Source root: {source_root}
 * Focus: {focus}
 * {n_strings} string tokens, {n_constants} numeric constants.
 * Corpus splice: {corpus_dir_repr}
 *
 * Structure-aware libFuzzer/AFL++ custom mutator. The dictionaries are
 * extracted from the project's own source code (string literals, #define
 * numeric constants, switch-case values, enum values), which gives the
 * fuzzer high-leverage tokens it would otherwise have to discover by chance.
 *
 * 50% of mutations delegate to the engine's default byte mutator so AFL's
 * randomisation is preserved.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <dirent.h>

size_t LLVMFuzzerMutate(uint8_t *data, size_t size, size_t max_size);

{arrays_block}
{corpus_block}

static uint32_t rnd(unsigned int *seed) {{
    *seed = (*seed) * 1103515245u + 12345u;
    return *seed;
}}

size_t LLVMFuzzerCustomMutator(uint8_t *data, size_t size,
                               size_t max_size, unsigned int seed) {{
    /* Half the time, leave it to the engine. */
    if ((seed & 1u) == 0u) {{
        return LLVMFuzzerMutate(data, size, max_size);
    }}

    unsigned int r = seed;
    int op = (int)(rnd(&r) % {n_ops}u);

    switch (op) {{
{splice_string_block}
{splice_constant_block}
{splice_corpus_block}
    }}
    return LLVMFuzzerMutate(data, size, max_size);
}}
"""


_SPLICE_STRING_OP = """\
    case 0: {{
        if (NUM_SMART_STRINGS == 0) return LLVMFuzzerMutate(data, size, max_size);
        const char *tok = kSmartStrings[rnd(&r) % NUM_SMART_STRINGS];
        size_t tlen = strlen(tok);
        if (tlen == 0 || size + tlen > max_size) {{
            return LLVMFuzzerMutate(data, size, max_size);
        }}
        size_t off = (size == 0) ? 0 : (rnd(&r) % (size + 1u));
        memmove(data + off + tlen, data + off, size - off);
        memcpy(data + off, tok, tlen);
        return size + tlen;
    }}
"""

_SPLICE_CONSTANT_OP = """\
    case 1: {{
        if (NUM_SMART_CONSTANTS == 0 || size + 4u > max_size) {{
            return LLVMFuzzerMutate(data, size, max_size);
        }}
        uint32_t c = kSmartConstants[rnd(&r) % NUM_SMART_CONSTANTS];
        size_t off = (size == 0) ? 0 : (rnd(&r) % (size + 1u));
        memmove(data + off + 4u, data + off, size - off);
        if ((seed & 2u) == 0u) {{
            /* little-endian */
            data[off + 0] = (uint8_t)(c & 0xffu);
            data[off + 1] = (uint8_t)((c >> 8) & 0xffu);
            data[off + 2] = (uint8_t)((c >> 16) & 0xffu);
            data[off + 3] = (uint8_t)((c >> 24) & 0xffu);
        }} else {{
            /* big-endian */
            data[off + 0] = (uint8_t)((c >> 24) & 0xffu);
            data[off + 1] = (uint8_t)((c >> 16) & 0xffu);
            data[off + 2] = (uint8_t)((c >> 8) & 0xffu);
            data[off + 3] = (uint8_t)(c & 0xffu);
        }}
        return size + 4u;
    }}
"""

# C5+: corpus-splice op. Reads a random file from kCorpusDir on first use,
# caches at most kMaxCorpusBytes per file, then splices a random sub-region
# of a random cached file into the input. Useful for "remix" mutations that
# preserve interesting structure discovered by AFL itself.
_CORPUS_BLOCK = """\
#ifndef SMART_MUTATOR_NO_CORPUS
#define SMART_MUTATOR_CORPUS_DIR {corpus_dir_c}
#define SMART_MUTATOR_MAX_CORPUS_FILES 64
#define SMART_MUTATOR_MAX_CORPUS_BYTES 4096

static struct {{
    int loaded;
    int n_files;
    uint8_t *data[SMART_MUTATOR_MAX_CORPUS_FILES];
    size_t size[SMART_MUTATOR_MAX_CORPUS_FILES];
}} kCorpus = {{0, 0, {{0}}, {{0}}}};

static void smart_mutator_load_corpus(void) {{
    if (kCorpus.loaded) return;
    kCorpus.loaded = 1;
    DIR *d = opendir(SMART_MUTATOR_CORPUS_DIR);
    if (!d) return;
    struct dirent *e;
    while ((e = readdir(d)) != NULL && kCorpus.n_files < SMART_MUTATOR_MAX_CORPUS_FILES) {{
        if (e->d_name[0] == '.') continue;
        char path[1024];
        int n = snprintf(path, sizeof(path), "%s/%s", SMART_MUTATOR_CORPUS_DIR, e->d_name);
        if (n <= 0 || (size_t)n >= sizeof(path)) continue;
        struct stat st;
        if (stat(path, &st) != 0 || !S_ISREG(st.st_mode)) continue;
        size_t sz = (size_t)st.st_size;
        if (sz == 0) continue;
        if (sz > SMART_MUTATOR_MAX_CORPUS_BYTES) sz = SMART_MUTATOR_MAX_CORPUS_BYTES;
        FILE *f = fopen(path, "rb");
        if (!f) continue;
        uint8_t *buf = (uint8_t *)malloc(sz);
        if (!buf) {{ fclose(f); continue; }}
        size_t got = fread(buf, 1, sz, f);
        fclose(f);
        if (got == 0) {{ free(buf); continue; }}
        kCorpus.data[kCorpus.n_files] = buf;
        kCorpus.size[kCorpus.n_files] = got;
        kCorpus.n_files++;
    }}
    closedir(d);
}}
#endif  /* SMART_MUTATOR_NO_CORPUS */
"""

_SPLICE_CORPUS_OP = """\
    case 2: {{
#ifndef SMART_MUTATOR_NO_CORPUS
        smart_mutator_load_corpus();
        if (kCorpus.n_files == 0) return LLVMFuzzerMutate(data, size, max_size);
        size_t fi = rnd(&r) % (uint32_t)kCorpus.n_files;
        size_t fsz = kCorpus.size[fi];
        if (fsz < 2) return LLVMFuzzerMutate(data, size, max_size);
        size_t span_start = rnd(&r) % fsz;
        size_t span_max = fsz - span_start;
        if (span_max > 64) span_max = 64;
        size_t span = (rnd(&r) % span_max) + 1;
        if (size + span > max_size) return LLVMFuzzerMutate(data, size, max_size);
        size_t off = (size == 0) ? 0 : (rnd(&r) % (size + 1u));
        memmove(data + off + span, data + off, size - off);
        memcpy(data + off, kCorpus.data[fi] + span_start, span);
        return size + span;
#else
        return LLVMFuzzerMutate(data, size, max_size);
#endif
    }}
"""


def _c_path_literal(p: str) -> str:
    """Render a filesystem path as a C string literal."""
    out: list[str] = []
    for ch in p:
        b = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= b <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\{b:03o}")
    return f'"{"".join(out)}"'


def _emit_smart_mutator_c(
    source_root: Path,
    focus: str,
    strings: list[str],
    constants: list[int],
    corpus_dir: str = "",
) -> str:
    """Render a self-contained LLVMFuzzerCustomMutator .c file.

    Only emits the arrays + case arms needed for the chosen focus, so the
    resulting C compiles cleanly under -Wunused-* -Werror.

    If ``corpus_dir`` is non-empty, also emits a corpus-splice op that loads
    files from that directory at first call and splices random sub-regions
    into the mutated input (C5+).
    """
    if focus == "strings":
        emit_strings, emit_constants = True, False
        used_strings = strings
        used_constants: list[int] = []
    elif focus == "constants":
        emit_strings, emit_constants = False, True
        used_strings = []
        used_constants = constants
    else:  # combined
        emit_strings, emit_constants = True, True
        used_strings = strings
        used_constants = constants

    string_arr = ""
    if emit_strings:
        if used_strings:
            rendered = ",\n    ".join(f'"{_c_string_escape(s)}"' for s in used_strings)
            string_arr = (
                f"static const char *kSmartStrings[] = {{\n    {rendered}\n}};\n"
                f"#define NUM_SMART_STRINGS (sizeof(kSmartStrings) / sizeof(kSmartStrings[0]))"
            )
        else:
            # Empty extraction; fall back to a tiny no-op array so the case-arm
            # can still compile without ifdefs.
            string_arr = (
                'static const char *kSmartStrings[1] = { "" };\n'
                "#define NUM_SMART_STRINGS 0u"
            )

    constant_arr = ""
    if emit_constants:
        if used_constants:
            rendered = ",\n    ".join(f"0x{c:08x}u" for c in used_constants)
            constant_arr = (
                f"static const uint32_t kSmartConstants[] = {{\n    {rendered}\n}};\n"
                f"#define NUM_SMART_CONSTANTS (sizeof(kSmartConstants) / sizeof(kSmartConstants[0]))"
            )
        else:
            constant_arr = (
                "static const uint32_t kSmartConstants[1] = { 0u };\n"
                "#define NUM_SMART_CONSTANTS 0u"
            )

    arrays_block = "\n".join(b for b in (string_arr, constant_arr) if b)

    splice_string_block = _SPLICE_STRING_OP.format() if emit_strings else ""
    splice_constant_block = _SPLICE_CONSTANT_OP.format() if emit_constants else ""

    emit_corpus = bool(corpus_dir)
    if emit_corpus:
        corpus_block = _CORPUS_BLOCK.format(corpus_dir_c=_c_path_literal(corpus_dir))
        splice_corpus_block = _SPLICE_CORPUS_OP
    else:
        corpus_block = ""
        splice_corpus_block = ""

    n_ops = sum([emit_strings, emit_constants, emit_corpus])
    if n_ops == 0:
        # Degenerate: no useful tokens. Fall back to a pass-through mutator.
        n_ops = 1
        splice_string_block = (
            "    case 0: { return LLVMFuzzerMutate(data, size, max_size); }\n"
        )
    elif n_ops == 1 and emit_constants:
        # Renumber the lone case to 0 for cleanliness.
        splice_constant_block = splice_constant_block.replace("case 1:", "case 0:", 1)
    elif n_ops == 1 and emit_corpus:
        splice_corpus_block = splice_corpus_block.replace("case 2:", "case 0:", 1)
    elif n_ops == 2 and emit_corpus and not emit_strings:
        # constants + corpus → cases 1 and 2; renumber to 0, 1.
        splice_constant_block = splice_constant_block.replace("case 1:", "case 0:", 1)
        splice_corpus_block = splice_corpus_block.replace("case 2:", "case 1:", 1)
    elif n_ops == 2 and emit_corpus and not emit_constants:
        # strings + corpus → cases 0 and 2; renumber 2 to 1.
        splice_corpus_block = splice_corpus_block.replace("case 2:", "case 1:", 1)

    return _SMART_MUTATOR_TEMPLATE.format(
        source_root=str(source_root),
        focus=focus,
        n_strings=len(used_strings),
        n_constants=len(used_constants),
        corpus_dir_repr=corpus_dir or "(disabled)",
        arrays_block=arrays_block,
        corpus_block=corpus_block,
        n_ops=n_ops,
        splice_string_block=splice_string_block,
        splice_constant_block=splice_constant_block,
        splice_corpus_block=splice_corpus_block,
    )


@mcp.tool()
def generate_smart_mutator(
    source_root: Annotated[str, Field(description="Path to the unpacked source tree (e.g. the repo root)")],
    output_path: Annotated[str, Field(description="Where to write the generated .c file")],
    focus: Annotated[str, Field(description="One of: strings, constants, combined. 'combined' splices both string tokens and 32-bit numeric magic values (recommended).")] = "combined",
    max_strings: Annotated[int, Field(description="Cap on the number of string tokens to embed")] = 192,
    max_constants: Annotated[int, Field(description="Cap on the number of numeric constants to embed")] = 96,
    max_string_len: Annotated[int, Field(description="Drop string literals longer than this many chars")] = 64,
    max_files: Annotated[int, Field(description="Cap on number of source files to scan")] = 800,
    corpus_dir: Annotated[str, Field(description="Optional: path to a corpus dir whose files the mutator should splice from at runtime (C5+). Typically the persistent corpus from get_persistent_corpus_dir.")] = "",
) -> dict:
    """Generate a project-specific structure-aware libFuzzer/AFL++ mutator by
    statically analysing the project's source code.

    The mutator embeds the most-frequent string literals and 32-bit numeric
    constants from the project's own ``.c``/``.h`` files. Splicing these
    tokens into AFL's mutated inputs lets the fuzzer hit branches gated on
    protocol keywords, magic numbers, and enum values that random byte
    mutation would otherwise need to discover by chance.

    When ``corpus_dir`` is set, the mutator also gets a corpus-splice op:
    on first call it loads up to 64 files from that dir (capped at 4 KiB
    each) and from then on can splice random sub-regions of those files
    into the mutated input. Pair with ``get_persistent_corpus_dir`` for
    "remix what AFL has already discovered" mutations.

    See :py:func:`generate_smart_mutators` for the multi-variant version
    (one mutator per focus, useful with ``HARNESS_CANDIDATES > 1``).
    """
    root = Path(source_root)
    if not root.is_dir():
        return {"ok": False, "error": f"source_root not found: {source_root}"}
    focus = focus.strip().lower()
    if focus not in ("strings", "constants", "combined"):
        return {"ok": False, "error": f"focus must be one of: strings, constants, combined; got {focus!r}"}

    tokens = _extract_project_tokens(
        root, max_files=max_files,
        max_strings=max_strings, max_constants=max_constants,
        max_string_len=max_string_len,
    )
    c_source = _emit_smart_mutator_c(
        root, focus, tokens["strings"], tokens["constants"], corpus_dir=corpus_dir,
    )
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(c_source)
    return {
        "ok": True,
        "mutator_source_path": str(out),
        "focus": focus,
        "strings_embedded": len(tokens["strings"]) if focus != "constants" else 0,
        "constants_embedded": len(tokens["constants"]) if focus != "strings" else 0,
        "corpus_dir": corpus_dir or "",
        "stats": tokens["stats"],
    }


@mcp.tool()
def generate_smart_mutators(
    source_root: Annotated[str, Field(description="Path to the unpacked source tree (e.g. the repo root)")],
    output_dir: Annotated[str, Field(description="Where to write the generated .c files (one per variant)")],
    basename: Annotated[str, Field(description="File-name prefix; the variants are <basename>_strings.c, <basename>_constants.c, <basename>_combined.c")] = "smart",
    max_strings: Annotated[int, Field(description="Cap on string tokens per mutator")] = 192,
    max_constants: Annotated[int, Field(description="Cap on numeric constants per mutator")] = 96,
    corpus_dir: Annotated[str, Field(description="Optional: path to a corpus dir; embeds the corpus-splice op in every variant.")] = "",
) -> dict:
    """Generate three variants of project-specific structure-aware mutators
    (strings-only, constants-only, combined) — one analysis pass, three .c
    files. Pair with ``HARNESS_CANDIDATES > 1`` so each variant becomes a
    candidate harness in the qualifier round.
    """
    root = Path(source_root)
    if not root.is_dir():
        return {"ok": False, "error": f"source_root not found: {source_root}"}
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    tokens = _extract_project_tokens(
        root, max_strings=max_strings, max_constants=max_constants,
    )
    variants = {}
    for focus in ("strings", "constants", "combined"):
        path = out_dir / f"{basename}_{focus}.c"
        path.write_text(_emit_smart_mutator_c(
            root, focus, tokens["strings"], tokens["constants"],
            corpus_dir=corpus_dir,
        ))
        variants[focus] = str(path)
    return {
        "ok": True,
        "variants": variants,
        "strings_total": len(tokens["strings"]),
        "constants_total": len(tokens["constants"]),
        "corpus_dir": corpus_dir or "",
        "stats": tokens["stats"],
    }


# ---------------------------------------------------------------------------
# Project-aware AFL dictionaries (pre-fuzzing + coverage-driven enrichment)
# ---------------------------------------------------------------------------

# Patterns that mark a "magic token guard" inside a C/C++ source line.
# These are the conditional branches we most often want AFL to satisfy:
#   strncmp(p, "BEGIN", 5)
#   strcmp(s, "POST")
#   memcmp(buf, "\x89PNG", 4)
#   strstr(s, "Content-Type")
#   if (foo == 0xDEADBEEF)
#   case 0xFEEDFACE:
_GUARD_STRING_RE = re.compile(
    r'\b(?:strn?cmp|strn?casecmp|memn?cmp|strn?str|strstartswith|starts_with)'
    r'\s*\([^)]*?"((?:[^"\\\n]|\\.){2,64})"',
)
# `if (... == "literal")` is rare in C, but `if (foo == 'X')` and char
# comparisons via numeric constants do occur — we capture both numeric and
# character forms.
_GUARD_NUM_RE = re.compile(
    r'(?:==|!=)\s*(0x[0-9a-fA-F]+|\d+)(?:[uUlL]+)?\b',
)
_GUARD_CHAR_RE = re.compile(r"(?:==|!=)\s*'((?:[^'\\]|\\.))'")
_GUARD_CASE_RE = re.compile(r'\bcase\s+(0x[0-9a-fA-F]+|-?\d+)(?:[uUlL]+)?\s*:')
_GUARD_CASE_CHAR_RE = re.compile(r"\bcase\s+'((?:[^'\\]|\\.))'\s*:")


def _afl_dict_escape(s: str) -> str:
    """Escape a Python string for an AFL ``-x`` dictionary entry value."""
    out: list[str] = []
    for ch in s:
        b = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= b <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


def _read_afl_dict_keys(path: Path) -> set[str]:
    """Return the set of escaped ``value`` strings already present in an AFL
    dictionary. We compare on the *escaped form* (what's written to the file)
    rather than decoded bytes, because that's what the file actually stores
    and round-tripping decoded bytes through unicode_escape gives different
    representations for the same logical token (e.g. ``\\x89`` vs the raw
    0x89 byte).
    """
    if not path.is_file():
        return set()
    seen: set[str] = set()
    for raw in path.read_text(errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Drop trailing comment (`# ...`) before parsing the value.
        comment_idx = line.find('"  #')
        if comment_idx == -1:
            comment_idx = line.find('" #')
        body = line[:comment_idx + 1] if comment_idx != -1 else line
        # name="value"
        _, _, rhs = body.partition("=")
        rhs = rhs.strip()
        if rhs.startswith('"') and rhs.endswith('"') and len(rhs) >= 2:
            seen.add(rhs[1:-1])
    return seen


def _append_to_afl_dict(
    path: Path,
    new_strings: list[str],
    new_constants: list[int],
    prefix: str = "kw",
) -> dict:
    """Append entries to an AFL dictionary at ``path`` (creates if missing).

    Idempotent: never re-adds an entry whose escaped form already appears.
    Returns counts of {added_strings, added_constants, total_after, skipped_existing}.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    existing_escaped = _read_afl_dict_keys(path)
    next_id = sum(
        1
        for raw in (path.read_text(errors="replace").splitlines() if path.is_file() else [])
        if "=" in raw and not raw.lstrip().startswith("#")
    )

    added_str = 0
    added_const = 0
    skipped = 0
    new_lines: list[str] = []
    if not path.is_file():
        new_lines.append("# AFL dictionary auto-generated by fuzz_runner")

    for s in new_strings:
        escaped = _afl_dict_escape(s)
        if escaped in existing_escaped:
            skipped += 1
            continue
        new_lines.append(f'{prefix}{next_id}="{escaped}"')
        existing_escaped.add(escaped)
        next_id += 1
        added_str += 1

    for c in new_constants:
        # Encode 32-bit constants in BOTH endiannesses so the fuzzer can
        # discover whichever the target uses for comparison.
        for label, raw in (("le", c.to_bytes(4, "little")), ("be", c.to_bytes(4, "big"))):
            val = raw.decode("latin-1")
            escaped = _afl_dict_escape(val)
            if escaped in existing_escaped:
                skipped += 1
                continue
            new_lines.append(f'{prefix}{next_id}="{escaped}"  # 0x{c:08x} {label}')
            existing_escaped.add(escaped)
            next_id += 1
            added_const += 1

    if new_lines:
        with path.open("a") as fh:
            for ln in new_lines:
                fh.write(ln + "\n")

    return {
        "added_strings": added_str,
        "added_constants": added_const,
        "skipped_existing": skipped,
        "total_after": len(existing_escaped),
        "dictionary_path": str(path),
    }


@mcp.tool()
def generate_project_dictionary(
    source_root: Annotated[str, Field(description="Path to the unpacked source tree (e.g. the repo root)")],
    output_path: Annotated[str, Field(description="Where to write the AFL dictionary file")],
    max_strings: Annotated[int, Field(description="Cap on string tokens to include")] = 256,
    max_constants: Annotated[int, Field(description="Cap on numeric constants to include")] = 96,
    max_string_len: Annotated[int, Field(description="Drop string literals longer than this many chars")] = 64,
    max_files: Annotated[int, Field(description="Cap on number of source files to scan")] = 800,
) -> dict:
    """Generate a project-specific AFL dictionary (``-x`` file) by scanning the
    project's source code for high-leverage tokens.

    Use this BEFORE iteration 1 of fuzzing so AFL has good splice tokens from
    the very first input. Reuses the same source-token extractor as
    :py:func:`generate_smart_mutator`, but writes an AFL dictionary file
    instead of a mutator. A complementary tool,
    :py:func:`enrich_dictionary_from_uncovered`, appends to this file after
    each iteration based on uncovered branches.
    """
    root = Path(source_root)
    if not root.is_dir():
        return {"ok": False, "error": f"source_root not found: {source_root}"}
    out = Path(output_path)
    tokens = _extract_project_tokens(
        root, max_files=max_files,
        max_strings=max_strings, max_constants=max_constants,
        max_string_len=max_string_len,
    )
    # If the file already exists, we ADD to it rather than overwriting — this
    # makes the tool safe to re-run during a campaign.
    result = _append_to_afl_dict(out, tokens["strings"], tokens["constants"], prefix="src")
    result["ok"] = True
    result["stats"] = tokens["stats"]
    return result


def _scan_uncovered_for_guards(
    source_root: Path,
    uncovered: list[dict],
    context_lines: int = 8,
    max_files: int = 200,
    max_per_file: int = 50,
) -> dict:
    """Walk uncovered (file, line) pairs and extract magic-token guards from
    the surrounding source.

    For each uncovered location, looks at the preceding ``context_lines``
    lines for ``strncmp(... "X")``, ``memcmp(... "X")``, ``case 0xN:``,
    ``== 0xN``, etc. — these are the conditionals AFL needs to satisfy to
    reach the uncovered code.
    """
    if not source_root.is_dir() or not uncovered:
        return {"strings": [], "constants": []}

    # Group uncovered rows by file for cheap reads.
    by_file: dict[str, list[int]] = {}
    for row in uncovered:
        fpath = row.get("file") or ""
        line = row.get("line") or 0
        if not fpath or not line:
            continue
        # The LCOV `file` is often an absolute path. Try both as-is and joined
        # to source_root.
        candidates = [Path(fpath)]
        if not Path(fpath).is_absolute():
            candidates.insert(0, source_root / fpath)
        for c in candidates:
            if c.is_file():
                by_file.setdefault(str(c), []).append(int(line))
                break

    strings_seen: set[str] = set()
    constants_seen: set[int] = set()
    files_scanned = 0

    for fpath, lines in by_file.items():
        if files_scanned >= max_files:
            break
        files_scanned += 1
        try:
            text = Path(fpath).read_text(errors="replace").splitlines()
        except OSError:
            continue
        per_file_count = 0
        for ln in lines:
            if per_file_count >= max_per_file:
                break
            # Look at the `context_lines` lines BEFORE the uncovered line —
            # that's where the guard lives. Also include the line itself in
            # case the comparison is on the same line as the call site.
            lo = max(0, ln - context_lines)
            hi = min(len(text), ln + 1)
            window = "\n".join(text[lo:hi])

            for m in _GUARD_STRING_RE.finditer(window):
                raw = m.group(1)
                try:
                    decoded = raw.encode("utf-8", errors="replace").decode("unicode_escape", errors="replace")
                except (UnicodeDecodeError, ValueError):
                    continue
                if 1 <= len(decoded) <= 64:
                    strings_seen.add(decoded)
                    per_file_count += 1
            for m in _GUARD_NUM_RE.finditer(window):
                try:
                    v = int(m.group(1), 0) & 0xFFFFFFFF
                except (ValueError, OverflowError):
                    continue
                if v in _NUMERIC_NOISE:
                    continue
                constants_seen.add(v)
                per_file_count += 1
            for m in _GUARD_CHAR_RE.finditer(window):
                ch = m.group(1)
                # Single-char comparisons are useful for splicing as 1-byte tokens.
                if len(ch) == 1:
                    strings_seen.add(ch)
                    per_file_count += 1
                elif ch.startswith("\\"):
                    try:
                        decoded = ch.encode("utf-8").decode("unicode_escape")
                        if decoded:
                            strings_seen.add(decoded)
                            per_file_count += 1
                    except (UnicodeDecodeError, ValueError):
                        pass
            for m in _GUARD_CASE_RE.finditer(window):
                try:
                    v = int(m.group(1), 0) & 0xFFFFFFFF
                except (ValueError, OverflowError):
                    continue
                if v not in _NUMERIC_NOISE:
                    constants_seen.add(v)
                    per_file_count += 1
            for m in _GUARD_CASE_CHAR_RE.finditer(window):
                ch = m.group(1)
                if len(ch) == 1:
                    strings_seen.add(ch)
                    per_file_count += 1

    return {
        "strings": sorted(strings_seen),
        "constants": sorted(constants_seen),
        "files_scanned": files_scanned,
    }


@mcp.tool()
def enrich_dictionary_from_uncovered(
    source_root: Annotated[str, Field(description="Path to the unpacked source tree (e.g. the repo root)")],
    dictionary_path: Annotated[str, Field(description="AFL dictionary file to APPEND to (created if missing)")],
    uncovered_locations: Annotated[list[dict], Field(description="List of {'file': '...', 'line': N} dicts. Pass the result of fuzz_context.get_coverage_gaps() filtered to kind='line' or kind='branch'.")],
    context_lines: Annotated[int, Field(description="Lines of preceding context to scan for guards near each uncovered line")] = 8,
    max_files: Annotated[int, Field(description="Cap on uncovered files to scan")] = 200,
) -> dict:
    """Coverage-driven AFL dictionary enrichment.

    For every uncovered (file, line) pair, this scans the surrounding source
    code for *guard expressions* — `strncmp(..., "TOKEN")`, `memcmp(..., 0xN)`,
    `case 0xN:`, `== 0xN`, etc. — and APPENDS any new tokens it finds to the
    given AFL dictionary. The next afl-fuzz run picks them up automatically.

    The tool is idempotent: it never re-adds a token already present in the
    dictionary.

    Typical usage at the bottom of a fuzz iteration::

        gaps = get_coverage_gaps(harness_id=H, kind='line', limit=200)
        enrich_dictionary_from_uncovered(
            source_root=<repo root>,
            dictionary_path=<seeds dir>/auto.dict,
            uncovered_locations=[{'file': g['file'], 'line': g['line']} for g in gaps],
        )
    """
    root = Path(source_root)
    if not root.is_dir():
        return {"ok": False, "error": f"source_root not found: {source_root}"}
    if not uncovered_locations:
        return {
            "ok": True, "added_strings": 0, "added_constants": 0,
            "skipped_existing": 0, "files_scanned": 0,
            "dictionary_path": dictionary_path,
        }

    found = _scan_uncovered_for_guards(
        root, uncovered_locations,
        context_lines=context_lines, max_files=max_files,
    )
    appended = _append_to_afl_dict(
        Path(dictionary_path), found["strings"], found["constants"], prefix="cov",
    )
    appended["ok"] = True
    appended["files_scanned"] = found["files_scanned"]
    appended["candidate_strings"] = len(found["strings"])
    appended["candidate_constants"] = len(found["constants"])
    return appended


if __name__ == "__main__":
    mcp.run(show_banner=False)
